[package]
name = "leapcell"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
redis = { version = "0.29.1", features = ["tls"] }
tokio = {  version = "1.44.0", features = ["macros", "rt-multi-thread"] }
chrono = "0.4.40"
